/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/bitshopb.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Bitshop({ position, selected }) {
  const { nodes, materials } = useGLTF("models/kingb.glb");
  return (
    <group
      //position={[position.x / 64, 0.1, position.y / 64]}
      scale={[0.3, 0.3, 0.3]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Black_bitshop.geometry}
        material={materials["Material.001"]}
      >
        {" "}
        {selected && <meshStandardMaterial color="green" />}
      </mesh>
    </group>
  );
}

useGLTF.preload("models/kingb.glb");
