/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/kingb.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function KingW({ position, selected }) {
  const { nodes, materials } = useGLTF("models/kingb.glb");
  return (
    <group
      position={[position.x / 64, 0.25, position.y / 64]}
      scale={[0.3, 0.3, 0.3]}
    >
      <mesh
        geometry={nodes.White_king.geometry}
        material={materials["Material.004"]}
        castShadow
        receiveShadow
      />
      {selected && <meshStandardMaterial color="green" />}
    </group>
  );
}

useGLTF.preload("models/kingb.glb");
